-- 2026-09-14 seen_ids 里还在、mart 里已不在的 43 行旧岗:district 按重建后的 FSA 表重算(与 mart normalize_jobbank_location 同规则)
BEGIN;
UPDATE jobs SET district = 'Fredericton South' WHERE external_id = 'jb:49833793' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:49868810' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:49882200' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Winnipeg' WHERE external_id = 'jb:49894026' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:49943624' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:49965515' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:49969670' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:49969997' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:49972462' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Charlottetown Southeast' WHERE external_id = 'jb:49973503' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Fredericton South' WHERE external_id = 'jb:49973543' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Winnipeg' WHERE external_id = 'jb:49974610' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50020842' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Fredericton South' WHERE external_id = 'jb:50030905' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Fredericton South' WHERE external_id = 'jb:50035304' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Fredericton South' WHERE external_id = 'jb:50035306' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Regina South' WHERE external_id = 'jb:50053731' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Regina South' WHERE external_id = 'jb:50055027' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Charlottetown Southeast' WHERE external_id = 'jb:50061212' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:50079518' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Broadway' WHERE external_id = 'jb:50079934' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50095368' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50095374' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50095383' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50113183' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50121378' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Broadway' WHERE external_id = 'jb:50145466' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50152514' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'St. John''s Northwest' WHERE external_id = 'jb:50153232' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Broadway' WHERE external_id = 'jb:50154658' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Regina South' WHERE external_id = 'jb:50155050' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:50183027' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50191148' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Regina South' WHERE external_id = 'jb:50193996' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jb:50196858' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Broadway' WHERE external_id = 'jb:50202193' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50243263' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50243271' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50249915' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Charlottetown Southeast' WHERE external_id = 'jb:50260944' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Halifax Mid-Harbour' WHERE external_id = 'jb:50267750' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = 'Victoria Central' WHERE external_id = 'jobboom:3688067' AND district LIKE '%Provincial Government%';
UPDATE jobs SET district = '' WHERE external_id = 'jobillico:17468469' AND district LIKE '%Provincial Government%';
COMMIT;
