/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    companies: Company;
    jobs: Job;
    'pnp-streams': PnpStream;
    'policy-docs': PolicyDoc;
    'designated-employers': DesignatedEmployer;
    provinces: Province;
    cities: City;
    districts: District;
    'noc-categories': NocCategory;
    sources: Source;
    'experience-levels': ExperienceLevel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'pnp-streams': PnpStreamsSelect<false> | PnpStreamsSelect<true>;
    'policy-docs': PolicyDocsSelect<false> | PolicyDocsSelect<true>;
    'designated-employers': DesignatedEmployersSelect<false> | DesignatedEmployersSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    'noc-categories': NocCategoriesSelect<false> | NocCategoriesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'experience-levels': ExperienceLevelsSelect<false> | ExperienceLevelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  slug?: string | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  region?: string | null;
  sectors?: string | null;
  address?: string | null;
  description?: string | null;
  isDesignatedEmployer?: boolean | null;
  /**
   * 中介/派遣 — 不会担保
   */
  isAgency?: boolean | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  company?: (number | null) | Company;
  /**
   * NOC 2021 5位码
   */
  noc?: string | null;
  /**
   * TEER 标签(=TEER X / 未分类)
   */
  category?: string | null;
  /**
   * NOC 第2位 0-5
   */
  teer?: number | null;
  /**
   * 大分类(NOC 第1位)
   */
  broad?: string | null;
  /**
   * 中分类
   */
  mid?: string | null;
  /**
   * 小分类
   */
  fine?: string | null;
  country?: string | null;
  province?: string | null;
  city?: string | null;
  /**
   * 社区/区(Kanata/Nepean/Orléans…)
   */
  district?: string | null;
  /**
   * 精确地址(街号+邮编)
   */
  address?: string | null;
  region?: string | null;
  /**
   * 第一方投递链接
   */
  applyUrl?: string | null;
  officialUrl?: string | null;
  /**
   * 原始薪资文本(悬停展示/搜索)
   */
  salary?: string | null;
  /**
   * 年薪折算(04d 清洗;排序/vs中位用)
   */
  salaryAnnual?: number | null;
  /**
   * 规范薪资文本(04d 清洗,如 $96K–$135K/yr)
   */
  salaryText?: string | null;
  datePosted?: string | null;
  /**
   * 原始来源板:indeed.com/Talent.com/lever/bamboohr…
   */
  source?: string | null;
  /**
   * 显示来源标签(mart 洗:JB→Job Bank、ATS板美化)
   */
  sourceLabel?: string | null;
  /**
   * 数据渠道:raw 下哪个来源
   */
  origin?: ('jobbank' | 'ats' | 'directory') | null;
  isAgency?: boolean | null;
  pnpStreams?: (number | PnpStream)[] | null;
  policyRefs?: (number | PolicyDoc)[] | null;
  accessibility?: ('co-op' | 'junior' | 'intermediate' | 'senior' | 'unknown') | null;
  /**
   * 移民价值评分 0-100
   */
  score?: number | null;
  /**
   * 可走雇主offer省提名(TEER0-3 或紧缺低TEER通道)
   */
  pnpEligible?: boolean | null;
  /**
   * 雇主在官方 AIP 指定雇主名单(大西洋四省 NL/NB/NS/PE)
   */
  aip?: boolean | null;
  firstSeen?: string | null;
  lastSeen?: string | null;
  status?: ('open' | 'closed') | null;
  /**
   * 下架时间(某次抓取不再出现)
   */
  closedAt?: string | null;
  /**
   * posting_id,用于增量去重
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-streams".
 */
export interface PnpStream {
  id: number;
  /**
   * 如 OINP-EJO / SINP-TECH
   */
  key?: string | null;
  name: string;
  province?: string | null;
  /**
   * EE对齐(有CRS地板)
   */
  isExpressEntry?: boolean | null;
  requiresJobOffer?: boolean | null;
  /**
   * base非EE,不看CRS
   */
  ignoresCRS?: boolean | null;
  officialUrl?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-docs".
 */
export interface PolicyDoc {
  id: number;
  title: string;
  stream?: (number | null) | PnpStream;
  province?: string | null;
  /**
   * 官方政策URL
   */
  sourceUrl?: string | null;
  /**
   * data/policy/ 下的本地原文路径
   */
  localPath?: string | null;
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designated-employers".
 */
export interface DesignatedEmployer {
  id: number;
  name: string;
  province?: string | null;
  location?: string | null;
  isTech?: boolean | null;
  /**
   * AIP官方名单来源(NL/NB/NS)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  /**
   * 2位省码,如 ON
   */
  code: string;
  /**
   * 全称,如 Ontario
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * 2位省码
   */
  province?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  city?: string | null;
  /**
   * 2位省码
   */
  province?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-categories".
 */
export interface NocCategory {
  id: number;
  /**
   * 大分类
   */
  broad?: string | null;
  /**
   * 中分类
   */
  mid?: string | null;
  /**
   * 小分类
   */
  fine?: string | null;
  teer?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-levels".
 */
export interface ExperienceLevel {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'pnp-streams';
        value: number | PnpStream;
      } | null)
    | ({
        relationTo: 'policy-docs';
        value: number | PolicyDoc;
      } | null)
    | ({
        relationTo: 'designated-employers';
        value: number | DesignatedEmployer;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'noc-categories';
        value: number | NocCategory;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'experience-levels';
        value: number | ExperienceLevel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  email?: T;
  phone?: T;
  region?: T;
  sectors?: T;
  address?: T;
  description?: T;
  isDesignatedEmployer?: T;
  isAgency?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  noc?: T;
  category?: T;
  teer?: T;
  broad?: T;
  mid?: T;
  fine?: T;
  country?: T;
  province?: T;
  city?: T;
  district?: T;
  address?: T;
  region?: T;
  applyUrl?: T;
  officialUrl?: T;
  salary?: T;
  salaryAnnual?: T;
  salaryText?: T;
  datePosted?: T;
  source?: T;
  sourceLabel?: T;
  origin?: T;
  isAgency?: T;
  pnpStreams?: T;
  policyRefs?: T;
  accessibility?: T;
  score?: T;
  pnpEligible?: T;
  aip?: T;
  firstSeen?: T;
  lastSeen?: T;
  status?: T;
  closedAt?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-streams_select".
 */
export interface PnpStreamsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  province?: T;
  isExpressEntry?: T;
  requiresJobOffer?: T;
  ignoresCRS?: T;
  officialUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-docs_select".
 */
export interface PolicyDocsSelect<T extends boolean = true> {
  title?: T;
  stream?: T;
  province?: T;
  sourceUrl?: T;
  localPath?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designated-employers_select".
 */
export interface DesignatedEmployersSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  location?: T;
  isTech?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  province?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-categories_select".
 */
export interface NocCategoriesSelect<T extends boolean = true> {
  broad?: T;
  mid?: T;
  fine?: T;
  teer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-levels_select".
 */
export interface ExperienceLevelsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}