/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    companies: Company;
    jobs: Job;
    'pnp-occupations': PnpOccupation;
    'pnp-draws': PnpDraw;
    dli: Dli;
    'ee-categories': EeCategory;
    'noc-descriptions': NocDescription;
    'policy-docs': PolicyDoc;
    'designated-employers': DesignatedEmployer;
    provinces: Province;
    cities: City;
    districts: District;
    'noc-categories': NocCategory;
    sources: Source;
    'experience-levels': ExperienceLevel;
    'field-sources': FieldSource;
    rankings: Ranking;
    stats: Stat;
    'saved-searches': SavedSearch;
    'saved-jobs': SavedJob;
    news: News;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'pnp-occupations': PnpOccupationsSelect<false> | PnpOccupationsSelect<true>;
    'pnp-draws': PnpDrawsSelect<false> | PnpDrawsSelect<true>;
    dli: DliSelect<false> | DliSelect<true>;
    'ee-categories': EeCategoriesSelect<false> | EeCategoriesSelect<true>;
    'noc-descriptions': NocDescriptionsSelect<false> | NocDescriptionsSelect<true>;
    'policy-docs': PolicyDocsSelect<false> | PolicyDocsSelect<true>;
    'designated-employers': DesignatedEmployersSelect<false> | DesignatedEmployersSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    'noc-categories': NocCategoriesSelect<false> | NocCategoriesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    'experience-levels': ExperienceLevelsSelect<false> | ExperienceLevelsSelect<true>;
    'field-sources': FieldSourcesSelect<false> | FieldSourcesSelect<true>;
    rankings: RankingsSelect<false> | RankingsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    'saved-searches': SavedSearchesSelect<false> | SavedSearchesSelect<true>;
    'saved-jobs': SavedJobsSelect<false> | SavedJobsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('user' | 'admin') | null;
  /**
   * Pro 到期日(时长包,webhook 写入;手动改=人工赠送)
   */
  proUntil?: string | null;
  stripeCustomerId?: string | null;
  stripeSessions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastAlertAt?: string | null;
  lastWeeklyAt?: string | null;
  /**
   * 退订每周收藏摘要邮件
   */
  weeklyOptOut?: boolean | null;
  /**
   * 昵称(空则前端回退邮箱前缀)
   */
  displayName?: string | null;
  /**
   * 头像 URL(v1 仅存 OAuth 带回的 URL,不做上传;无则前端画首字母块)
   */
  avatar?: string | null;
  /**
   * 注册来路:email(默认)/google/wechat
   */
  loginProvider?: string | null;
  /**
   * 界面/邮件语言 zh/en/ko(现仅 localStorage,落库备邮件用)
   */
  locale?: string | null;
  profile?: {
    /**
     * 分型 slug:overseas/studying/working/jobhunting/pr(界面大白话,幕后存码)
     */
    currentStatus?: string | null;
    /**
     * 经验/学历对应 NOC 码(string[])
     */
    nocCodes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * 语言 CLB 等级(自报)
     */
    clb?: number | null;
    /**
     * EE CRS 分(自报,可空)
     */
    crs?: number | null;
    /**
     * 目标省(省码 string[])
     */
    targetProvinces?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * PGWP 剩余月数
     */
    pgwpMonthsLeft?: number | null;
    profileUpdatedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  slug?: string | null;
  website?: string | null;
  /**
   * 官网来路:空=雇主自报/名录;jd=帖内线索;searched=自动检索(前端加小字,E8-04 D2)
   */
  websiteSource?: string | null;
  email?: string | null;
  phone?: string | null;
  region?: string | null;
  sectors?: string | null;
  address?: string | null;
  description?: string | null;
  isDesignatedEmployer?: boolean | null;
  /**
   * 中介/派遣 — 不会担保
   */
  isAgency?: boolean | null;
  source?: string | null;
  /**
   * 获批 LMIA 职位数(近两年)
   */
  lmiaPositions?: number | null;
  /**
   * 获批 LMIA 份数(近两年)
   */
  lmiaLmias?: number | null;
  /**
   * 最近获批季度,如 2025Q4
   */
  lmiaLastQuarter?: string | null;
  /**
   * 股别分布(展示串),如 High Wage 44 · Low Wage 12
   */
  lmiaStreams?: string | null;
  /**
   * AI 检索整理的公司简介(懒生成)
   */
  aiBrief?: string | null;
  /**
   * AI 检索到的官网(非库内 directory 原有,前端标注区分)
   */
  aiWebsite?: string | null;
  /**
   * 检索出处 URL 列表(JSON 数组串)
   */
  aiSources?: string | null;
  /**
   * AI 调查时间
   */
  aiFetched?: string | null;
  /**
   * 主营行业(NOC 大类多数派,数据层算)
   */
  industry?: string | null;
  /**
   * 中文别名(Wikidata zh 标签,查不到留空)
   */
  aliasZh?: string | null;
  /**
   * 韩文别名(Wikidata ko 标签)
   */
  aliasKo?: string | null;
  /**
   * Wikipedia 条目(非空=知名徽标)
   */
  wikiUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  company?: (number | null) | Company;
  /**
   * NOC 2021 5位码
   */
  noc?: string | null;
  /**
   * TEER 标签(=TEER X / 未分类)
   */
  category?: string | null;
  /**
   * NOC 第2位 0-5
   */
  teer?: number | null;
  /**
   * 大分类(NOC 第1位)
   */
  broad?: string | null;
  /**
   * 中分类
   */
  mid?: string | null;
  /**
   * 小分类
   */
  fine?: string | null;
  /**
   * 真实抓取的 JD 正文(mart 按 applyUrl 匹配 .md 写入);列表 SQL 不读,只「职位描述」弹框/顾问按需取
   */
  description?: string | null;
  country?: string | null;
  province?: string | null;
  city?: string | null;
  /**
   * 社区/区(Kanata/Nepean/Orléans…)
   */
  district?: string | null;
  /**
   * 精确地址(街号+邮编)
   */
  address?: string | null;
  region?: string | null;
  /**
   * 第一方投递链接(/api/jobtext 按此等值查询)
   */
  applyUrl?: string | null;
  officialUrl?: string | null;
  /**
   * 原始薪资文本(悬停展示/搜索)
   */
  salary?: string | null;
  /**
   * 年薪折算(04d 清洗;排序/vs中位用)
   */
  salaryAnnual?: number | null;
  /**
   * 规范薪资文本(04d 清洗,如 $96K–$135K/yr)
   */
  salaryText?: string | null;
  /**
   * 该 NOC 当地中位时薪(ESDC 开放数据,省级)
   */
  wageMedHourly?: number | null;
  /**
   * 该 NOC 当地中位年薪(=中位时薪×2080)
   */
  wageMedAnnual?: number | null;
  /**
   * 该 NOC 当地低位时薪(ESDC，可能缺)
   */
  wageLowHourly?: number | null;
  /**
   * 该 NOC 当地低位年薪
   */
  wageLowAnnual?: number | null;
  /**
   * 该 NOC 当地高位时薪(ESDC，可能缺)
   */
  wageHighHourly?: number | null;
  /**
   * 该 NOC 当地高位年薪
   */
  wageHighAnnual?: number | null;
  /**
   * ESDC 工资数据参考年份(如 2023-2024)
   */
  wageYear?: string | null;
  datePosted?: string | null;
  /**
   * 原始来源板:indeed.com/Talent.com/lever/bamboohr…
   */
  source?: string | null;
  /**
   * 显示来源标签(mart 洗:JB→Job Bank、ATS板美化)
   */
  sourceLabel?: string | null;
  /**
   * 数据渠道:raw 下哪个来源
   */
  origin?: ('jobbank' | 'ats' | 'directory') | null;
  isAgency?: boolean | null;
  policyRefs?: (number | PolicyDoc)[] | null;
  accessibility?: ('co-op' | 'junior' | 'intermediate' | 'senior' | 'unknown') | null;
  /**
   * 移民价值评分 0-100
   */
  score?: number | null;
  /**
   * 可走雇主offer省提名(TEER0-3 或紧缺低TEER通道)
   */
  pnpEligible?: boolean | null;
  /**
   * 命中省提名具名通道的短标签(如「OINP 紧缺技能」),数据层 08_score 算;泛技能岗为空
   */
  pnpStream?: string | null;
  /**
   * 联邦 Express Entry 类别抽选所属类别(医疗社服/STEM/技工…),数据层 08_score 算;与 PNP 是两条路,独立信号
   */
  eeCategory?: string | null;
  /**
   * 雇主在官方 AIP 指定雇主名单(大西洋四省 NL/NB/NS/PE)
   */
  aip?: boolean | null;
  /**
   * 雇佣期 permanent/term/casual/seasonal;空=未标注
   */
  employmentTerm?: string | null;
  /**
   * 工时 full/part;空=未标注
   */
  employmentHours?: string | null;
  /**
   * AI 五节整理版([ROLE]/[REQS]/[PAY]/[HOURS]/[APPLY] 标记文本,懒生成)
   */
  jdFormatted?: string | null;
  /**
   * 整理时间
   */
  jdFormattedAt?: string | null;
  /**
   * 证书/执照要求 string[](详情页 Certificates 区原文,标准化词表)
   */
  certificates?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 学历要求(详情页 Education 区原文,分号连接)
   */
  education?: string | null;
  firstSeen?: string | null;
  lastSeen?: string | null;
  status?: ('open' | 'closed') | null;
  /**
   * 下架时间(某次抓取不再出现)
   */
  closedAt?: string | null;
  /**
   * posting_id,用于增量去重
   */
  externalId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-docs".
 */
export interface PolicyDoc {
  id: number;
  title: string;
  province?: string | null;
  /**
   * 官方政策URL
   */
  sourceUrl?: string | null;
  /**
   * data/policy/ 下的本地原文路径
   */
  localPath?: string | null;
  body?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-occupations".
 */
export interface PnpOccupation {
  id: number;
  province?: string | null;
  /**
   * 通道官方名(英文)
   */
  stream?: string | null;
  /**
   * 通道短标签(前端显示,如「OINP 紧缺技能」)
   */
  label?: string | null;
  /**
   * indemand(命中=符合) / ineligible(命中=不符合)
   */
  type?: string | null;
  noc?: string | null;
  name?: string | null;
  /**
   * ON 限大多伦多区域外
   */
  gtaRestricted?: boolean | null;
  url?: string | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-draws".
 */
export interface PnpDraw {
  id: number;
  province?: string | null;
  /**
   * draw=抽选 / notice=改制通告
   */
  kind?: string | null;
  /**
   * 抽选日期(ISO)
   */
  drawDate?: string | null;
  /**
   * 流/通道名(官方原文)
   */
  stream?: string | null;
  /**
   * 最低邀请分 — 省自评分制,非 CRS!展示必须带 scale
   */
  score?: number | null;
  /**
   * 分制名(SIRS/WEOI/MPNP EOI)
   */
  scale?: string | null;
  invitations?: number | null;
  /**
   * 选择参数/期号/通告原文
   */
  note?: string | null;
  /**
   * 省项目名(BC PNP Skills Immigration/AAIP/…)
   */
  label?: string | null;
  url?: string | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dli".
 */
export interface Dli {
  id: number;
  province?: string | null;
  /**
   * 院校名(官方原文)
   */
  name?: string | null;
  /**
   * DLI 编号(O 开头,IRCC 官方)
   */
  dliNumber?: string | null;
  /**
   * 主校区城市(首行)
   */
  city?: string | null;
  /**
   * 名单内校区行数
   */
  campuses?: number | null;
  /**
   * 公立院校
   */
  isPublic?: boolean | null;
  /**
   * 有免 PAL/TAL 的研究生学位项目(官方列标)
   */
  gradProgram?: boolean | null;
  /**
   * 出处=IRCC DLI 名单页(着陆页)
   */
  url?: string | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ee-categories".
 */
export interface EeCategory {
  id: number;
  /**
   * 类别 key(healthcare/stem/…)
   */
  category?: string | null;
  /**
   * 类别中文标签(医疗社服/STEM/…)
   */
  label?: string | null;
  noc?: string | null;
  teer?: number | null;
  title?: string | null;
  url?: string | null;
  fetched?: string | null;
  /**
   * 该类别最近一次抽选 CRS 分数线
   */
  drawCrs?: number | null;
  /**
   * 该类别最近一次抽选日期
   */
  drawDate?: string | null;
  /**
   * 该类别最近一次抽选发出邀请数
   */
  drawSize?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-descriptions".
 */
export interface NocDescription {
  id: number;
  /**
   * NOC 2021 5 位码
   */
  noc?: string | null;
  /**
   * 官方职业名(Class title)
   */
  title?: string | null;
  /**
   * 主要职责(换行分隔)
   */
  duties?: string | null;
  /**
   * 任职要求(换行分隔)
   */
  requirements?: string | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designated-employers".
 */
export interface DesignatedEmployer {
  id: number;
  name: string;
  province?: string | null;
  location?: string | null;
  isTech?: boolean | null;
  /**
   * AIP官方名单来源(NL/NB/NS)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  /**
   * 2位省码,如 ON
   */
  code: string;
  /**
   * 全称,如 Ontario
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * 2位省码
   */
  province?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  city?: string | null;
  /**
   * 2位省码
   */
  province?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-categories".
 */
export interface NocCategory {
  id: number;
  /**
   * 大分类
   */
  broad?: string | null;
  /**
   * 中分类
   */
  mid?: string | null;
  /**
   * 小分类
   */
  fine?: string | null;
  teer?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-levels".
 */
export interface ExperienceLevel {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-sources".
 */
export interface FieldSource {
  id: number;
  /**
   * 前端字段键(ColKey/弹框字段)
   */
  field?: string | null;
  /**
   * dataset=外部数据集 | derived=本站派生
   */
  kind?: string | null;
  publisher?: string | null;
  url?: string | null;
  /**
   * 来源页 <title> 原文(不经 LLM 不翻译)
   */
  title?: string | null;
  /**
   * 来源页 meta description 原文
   */
  description?: string | null;
  /**
   * verified | unverified | derived
   */
  status?: string | null;
  fetched?: string | null;
  /**
   * 派生字段的本站口径说明
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings".
 */
export interface Ranking {
  id: number;
  /**
   * 榜单 slug(weekly-top / sponsor-likely)
   */
  slug?: string | null;
  rank?: number | null;
  /**
   * job | company
   */
  kind?: string | null;
  /**
   * kind=job:回 /jobs 定位用
   */
  externalId?: string | null;
  title?: string | null;
  company?: string | null;
  companySlug?: string | null;
  city?: string | null;
  province?: string | null;
  noc?: string | null;
  teer?: number | null;
  score?: number | null;
  salaryText?: string | null;
  salaryAnnual?: number | null;
  pnpStream?: string | null;
  eeCategory?: string | null;
  datePosted?: string | null;
  applyUrl?: string | null;
  officialUrl?: string | null;
  openJobs?: number | null;
  namedJobs?: number | null;
  avgScore?: number | null;
  lmiaPositions?: number | null;
  lmiaQuarter?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  province?: string | null;
  /**
   * NOC 大类(数据值)| all=省级汇总
   */
  broad?: string | null;
  /**
   * NOC 中类(数据值)| all=大类汇总(下钻 L2,2026-07-19)
   */
  mid?: string | null;
  /**
   * 在招岗数(本站抓取口径)
   */
  openJobs?: number | null;
  /**
   * 7 天新增(datePosted 近 7 天)
   */
  new7d?: number | null;
  /**
   * 中位年薪(ESDC 口径:桶内各岗 NOC×省中位的中位数)
   */
  medianWageAnnual?: number | null;
  /**
   * 帖面中位年薪(本站折算口径,对照)
   */
  medianSalaryAnnual?: number | null;
  /**
   * 省具名通道命中岗数
   */
  namedJobs?: number | null;
  /**
   * 命中的通道名(、分隔)
   */
  streamLabels?: string | null;
  aipJobs?: number | null;
  /**
   * json:[{city,n}] 前 5 城市
   */
  topCities?: string | null;
  /**
   * E12-07 省难度指数(仅 broad=all 行;{tier,factors[]} 带出处)
   */
  difficulty?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches".
 */
export interface SavedSearch {
  id: number;
  user: number | User;
  name: string;
  /**
   * /jobs 前端筛选 state 原样(jobsSql 解释)
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 存时的界面语言(zh/en/ko),发信用
   */
  lang?: string | null;
  /**
   * 上次发信游标(alerts run 回写,防重复通知)
   */
  lastNotifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs".
 */
export interface SavedJob {
  id: number;
  user: number | User;
  job?: (number | null) | Job;
  /**
   * 岗位标题快照(岗位下架后看板仍可读)
   */
  title?: string | null;
  /**
   * 公司名快照
   */
  company?: string | null;
  /**
   * wish | applied | interview | offer(前端下拉限定)
   */
  status?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * federal / BC / AB / SK / MB / ON / QC / NS
   */
  region?: string | null;
  /**
   * 官方原标题
   */
  title?: string | null;
  /**
   * 官方发布日期(ISO)
   */
  date?: string | null;
  /**
   * date+标题 slug(/news/[slug])
   */
  slug?: string | null;
  /**
   * 官方原文链接(详情页导流)
   */
  url?: string | null;
  /**
   * og:image 直链(hotlink,onerror 隐藏,不落盘)
   */
  ogImage?: string | null;
  /**
   * 清洗后摘要(mart 剥样板前缀/标题复读,P1c)
   */
  excerpt?: string | null;
  /**
   * AI 重要度 1-5(P1d,对找工/移民读者的实际影响;徽标用,非资格判定)
   */
  importance?: number | null;
  /**
   * AI 重要度一句理由(中文)
   */
  importanceNote?: string | null;
  /**
   * 官方英文原文全文(详情页主体,v3)
   */
  bodyEn?: string | null;
  /**
   * AI 段对段中文翻译(编号协议对齐,中文界面对照开关)
   */
  bodyZh?: string | null;
  /**
   * AI 中文速读(banner 轮播摘要)
   */
  summaryZh?: string | null;
  /**
   * AI 段对段韩语翻译(韩语界面对照开关)
   */
  bodyKo?: string | null;
  /**
   * AI 韩语速读(韩语界面 banner 摘要)
   */
  summaryKo?: string | null;
  /**
   * AI 英文速读(P1f 懒生成缓存)
   */
  summaryEn?: string | null;
  /**
   * 来源列表页(数据集级出处)
   */
  citation?: string | null;
  fetched?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  user: number | User;
  /**
   * 所评新闻 slug(/news/[slug])
   */
  newsSlug?: string | null;
  /**
   * 脱敏昵称快照(公开显示用,不回 user 关系)
   */
  authorName?: string | null;
  body: string;
  /**
   * pending(默认,不公开)/ approved / rejected —— admin 审核台改
   */
  status?: string | null;
  /**
   * 楼中楼:指向顶层楼(一层封顶,hook 校验);空=顶层
   */
  parent?: (number | null) | Comment;
  /**
   * 置顶楼(admin 专属;配合 admin 号发的评论=官方置顶)
   */
  pinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'pnp-occupations';
        value: number | PnpOccupation;
      } | null)
    | ({
        relationTo: 'pnp-draws';
        value: number | PnpDraw;
      } | null)
    | ({
        relationTo: 'dli';
        value: number | Dli;
      } | null)
    | ({
        relationTo: 'ee-categories';
        value: number | EeCategory;
      } | null)
    | ({
        relationTo: 'noc-descriptions';
        value: number | NocDescription;
      } | null)
    | ({
        relationTo: 'policy-docs';
        value: number | PolicyDoc;
      } | null)
    | ({
        relationTo: 'designated-employers';
        value: number | DesignatedEmployer;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'noc-categories';
        value: number | NocCategory;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'experience-levels';
        value: number | ExperienceLevel;
      } | null)
    | ({
        relationTo: 'field-sources';
        value: number | FieldSource;
      } | null)
    | ({
        relationTo: 'rankings';
        value: number | Ranking;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'saved-searches';
        value: number | SavedSearch;
      } | null)
    | ({
        relationTo: 'saved-jobs';
        value: number | SavedJob;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  proUntil?: T;
  stripeCustomerId?: T;
  stripeSessions?: T;
  lastAlertAt?: T;
  lastWeeklyAt?: T;
  weeklyOptOut?: T;
  displayName?: T;
  avatar?: T;
  loginProvider?: T;
  locale?: T;
  profile?:
    | T
    | {
        currentStatus?: T;
        nocCodes?: T;
        clb?: T;
        crs?: T;
        targetProvinces?: T;
        pgwpMonthsLeft?: T;
        profileUpdatedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  websiteSource?: T;
  email?: T;
  phone?: T;
  region?: T;
  sectors?: T;
  address?: T;
  description?: T;
  isDesignatedEmployer?: T;
  isAgency?: T;
  source?: T;
  lmiaPositions?: T;
  lmiaLmias?: T;
  lmiaLastQuarter?: T;
  lmiaStreams?: T;
  aiBrief?: T;
  aiWebsite?: T;
  aiSources?: T;
  aiFetched?: T;
  industry?: T;
  aliasZh?: T;
  aliasKo?: T;
  wikiUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  noc?: T;
  category?: T;
  teer?: T;
  broad?: T;
  mid?: T;
  fine?: T;
  description?: T;
  country?: T;
  province?: T;
  city?: T;
  district?: T;
  address?: T;
  region?: T;
  applyUrl?: T;
  officialUrl?: T;
  salary?: T;
  salaryAnnual?: T;
  salaryText?: T;
  wageMedHourly?: T;
  wageMedAnnual?: T;
  wageLowHourly?: T;
  wageLowAnnual?: T;
  wageHighHourly?: T;
  wageHighAnnual?: T;
  wageYear?: T;
  datePosted?: T;
  source?: T;
  sourceLabel?: T;
  origin?: T;
  isAgency?: T;
  policyRefs?: T;
  accessibility?: T;
  score?: T;
  pnpEligible?: T;
  pnpStream?: T;
  eeCategory?: T;
  aip?: T;
  employmentTerm?: T;
  employmentHours?: T;
  jdFormatted?: T;
  jdFormattedAt?: T;
  certificates?: T;
  education?: T;
  firstSeen?: T;
  lastSeen?: T;
  status?: T;
  closedAt?: T;
  externalId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-occupations_select".
 */
export interface PnpOccupationsSelect<T extends boolean = true> {
  province?: T;
  stream?: T;
  label?: T;
  type?: T;
  noc?: T;
  name?: T;
  gtaRestricted?: T;
  url?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pnp-draws_select".
 */
export interface PnpDrawsSelect<T extends boolean = true> {
  province?: T;
  kind?: T;
  drawDate?: T;
  stream?: T;
  score?: T;
  scale?: T;
  invitations?: T;
  note?: T;
  label?: T;
  url?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dli_select".
 */
export interface DliSelect<T extends boolean = true> {
  province?: T;
  name?: T;
  dliNumber?: T;
  city?: T;
  campuses?: T;
  isPublic?: T;
  gradProgram?: T;
  url?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ee-categories_select".
 */
export interface EeCategoriesSelect<T extends boolean = true> {
  category?: T;
  label?: T;
  noc?: T;
  teer?: T;
  title?: T;
  url?: T;
  fetched?: T;
  drawCrs?: T;
  drawDate?: T;
  drawSize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-descriptions_select".
 */
export interface NocDescriptionsSelect<T extends boolean = true> {
  noc?: T;
  title?: T;
  duties?: T;
  requirements?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-docs_select".
 */
export interface PolicyDocsSelect<T extends boolean = true> {
  title?: T;
  province?: T;
  sourceUrl?: T;
  localPath?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designated-employers_select".
 */
export interface DesignatedEmployersSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  location?: T;
  isTech?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  province?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noc-categories_select".
 */
export interface NocCategoriesSelect<T extends boolean = true> {
  broad?: T;
  mid?: T;
  fine?: T;
  teer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-levels_select".
 */
export interface ExperienceLevelsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-sources_select".
 */
export interface FieldSourcesSelect<T extends boolean = true> {
  field?: T;
  kind?: T;
  publisher?: T;
  url?: T;
  title?: T;
  description?: T;
  status?: T;
  fetched?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rankings_select".
 */
export interface RankingsSelect<T extends boolean = true> {
  slug?: T;
  rank?: T;
  kind?: T;
  externalId?: T;
  title?: T;
  company?: T;
  companySlug?: T;
  city?: T;
  province?: T;
  noc?: T;
  teer?: T;
  score?: T;
  salaryText?: T;
  salaryAnnual?: T;
  pnpStream?: T;
  eeCategory?: T;
  datePosted?: T;
  applyUrl?: T;
  officialUrl?: T;
  openJobs?: T;
  namedJobs?: T;
  avgScore?: T;
  lmiaPositions?: T;
  lmiaQuarter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  province?: T;
  broad?: T;
  mid?: T;
  openJobs?: T;
  new7d?: T;
  medianWageAnnual?: T;
  medianSalaryAnnual?: T;
  namedJobs?: T;
  streamLabels?: T;
  aipJobs?: T;
  topCities?: T;
  difficulty?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-searches_select".
 */
export interface SavedSearchesSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  filters?: T;
  lang?: T;
  lastNotifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-jobs_select".
 */
export interface SavedJobsSelect<T extends boolean = true> {
  user?: T;
  job?: T;
  title?: T;
  company?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  region?: T;
  title?: T;
  date?: T;
  slug?: T;
  url?: T;
  ogImage?: T;
  excerpt?: T;
  importance?: T;
  importanceNote?: T;
  bodyEn?: T;
  bodyZh?: T;
  summaryZh?: T;
  bodyKo?: T;
  summaryKo?: T;
  summaryEn?: T;
  citation?: T;
  fetched?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  user?: T;
  newsSlug?: T;
  authorName?: T;
  body?: T;
  status?: T;
  parent?: T;
  pinned?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}