'use client'
// 免责声明全文(E4-02,替换 E4-01 占位)。文案模板级自拟,不构成法律意见。
import { LegalShell, type LegalDoc } from '../LegalShell'
import { IconScale } from '../../Icons'
import type { Lang } from '../../jobs/i18n'

const docs: Record<Lang, LegalDoc> = {
  zh: {
    title: '免责声明',
    updated: '生效日期:2026-07-04',
    sections: [
      { h: '1. 本站性质', body: [
        'PNP Job Tracker 是一个职位信息聚合工具:数据来自 Job Bank、各省政府官网、IRCC、ESDC、加拿大统计局等公开来源的自动抓取、清洗与评分,每日更新。本站不是招聘中介,不代表任何雇主,也不参与任何招聘或移民申请流程。',
      ] },
      { h: '2. 非移民建议、非法律建议', body: [
        '本站全部内容——包括职位标记(PNP / EE 类别 / AIP)、评分、「与我的匹配」、AI 顾问输出——均不构成移民建议或法律建议。我们不是加拿大持牌移民顾问(RCIC),也不是律师,与 IRCC 及任何政府机构无隶属关系。',
        '任何移民决定请以 IRCC 与各省政府的官方发布为准,必要时咨询持牌专业人士。',
      ] },
      { h: '3. 标记与匹配是机械比对,非资格认定', body: [
        'PNP「可提名」等标记是按职业分类(NOC/TEER)与各省公开清单做的粗筛信号;「与我的匹配」是你自报档案与公开清单、抽选数据的机械比对。它们都不是任何形式的资格认定——各省项目另有语言、工资、学历、雇主资质等要求,且政策随时变化。',
      ] },
      { h: '4. 数据准确性', body: [
        '自动抓取的数据可能有误、缺失或滞后:职位可能已下架、薪资可能变动、清单与抽选线以官方页面实时为准。每条清单类数据我们尽量标注来源链接与抓取日期,便于你核对原始出处。',
      ] },
      { h: '5. AI 生成内容', body: [
        'AI 顾问的判断与对话由大语言模型生成,虽然我们要求它只基于本站核验过的数据回答,它仍可能出错或表述不准。AI 输出仅供参考,不构成任何建议。',
      ] },
      { h: '6. 外部链接', body: [
        '本站链接的官方原帖、政府页面等外部网站由第三方运营,其内容与可用性不在我们控制范围内。',
      ] },
    ],
  },
  en: {
    title: 'Disclaimer',
    updated: 'Effective date: 2026-07-04',
    sections: [
      { h: '1. What this site is', body: [
        'PNP Job Tracker is a job-information aggregator: data is automatically scraped, cleaned and scored from public sources such as Job Bank, provincial government websites, IRCC, ESDC and Statistics Canada, updated daily. We are not a recruitment agency, do not represent any employer, and are not involved in any hiring or immigration application process.',
      ] },
      { h: '2. Not immigration or legal advice', body: [
        'Nothing on this site — including job flags (PNP / EE category / AIP), scores, "Match for me", or AI advisor output — constitutes immigration or legal advice. We are not licensed Canadian immigration consultants (RCIC) or lawyers, and are not affiliated with IRCC or any government body.',
        'For any immigration decision, rely on official IRCC and provincial publications, and consult a licensed professional where needed.',
      ] },
      { h: '3. Flags and matches are mechanical comparisons, not eligibility rulings', body: [
        'PNP flags are rough screens based on occupation classification (NOC/TEER) against published provincial lists; "Match for me" mechanically compares your self-reported profile against published lists and draw data. None of these are eligibility determinations — provincial programs have additional language, wage, education and employer requirements, and policies change frequently.',
      ] },
      { h: '4. Data accuracy', body: [
        'Auto-scraped data may be wrong, incomplete or out of date: postings may have closed, wages may have changed, and lists / draw cutoffs are governed by the live official pages. Where possible we label list-type data with its source link and fetch date so you can verify the original.',
      ] },
      { h: '5. AI-generated content', body: [
        'AI advisor assessments and chat replies are generated by a large language model. Although we require it to answer only from data verified on this site, it can still be wrong or imprecise. AI output is for reference only.',
      ] },
      { h: '6. External links', body: [
        'Official postings, government pages and other external sites we link to are operated by third parties; their content and availability are outside our control.',
      ] },
    ],
  },
  ko: {
    title: '면책 조항',
    updated: '시행일: 2026-07-04',
    sections: [
      { h: '1. 본 사이트의 성격', body: [
        'PNP Job Tracker는 채용 정보 수집 도구입니다. Job Bank, 주정부 웹사이트, IRCC, ESDC, 캐나다 통계청 등 공개 출처에서 자동 수집·정제·평가한 데이터를 매일 갱신합니다. 당사는 채용 중개사가 아니며, 어떤 고용주도 대리하지 않고, 채용·이민 신청 절차에 관여하지 않습니다.',
      ] },
      { h: '2. 이민·법률 자문이 아님', body: [
        '본 사이트의 모든 콘텐츠(PNP / EE 카테고리 / AIP 표시, 점수, "나와의 매칭", AI 어드바이저 출력 포함)는 이민 또는 법률 자문이 아닙니다. 당사는 캐나다 공인 이민 컨설턴트(RCIC)나 변호사가 아니며 IRCC 및 정부 기관과 무관합니다.',
        '이민 관련 결정은 IRCC 및 주정부 공식 발표를 기준으로 하고, 필요 시 공인 전문가와 상담하세요.',
      ] },
      { h: '3. 표시와 매칭은 기계적 비교이며 자격 판정이 아님', body: [
        'PNP 표시는 직업 분류(NOC/TEER)와 주정부 공개 목록의 대략적 비교 신호이며, "나와의 매칭"은 자가 보고 프로필과 공개 목록·추첨 데이터의 기계적 비교입니다. 어느 것도 자격 판정이 아닙니다. 주정부 프로그램에는 언어·임금·학력·고용주 요건이 추가로 있으며 정책은 수시로 변합니다.',
      ] },
      { h: '4. 데이터 정확성', body: [
        '자동 수집 데이터는 오류·누락·지연이 있을 수 있습니다. 공고가 마감되었거나 급여가 변경되었을 수 있으며, 목록과 추첨 커트라인은 공식 페이지 기준입니다. 목록형 데이터에는 가능한 한 출처 링크와 수집일을 표기합니다.',
      ] },
      { h: '5. AI 생성 콘텐츠', body: [
        'AI 어드바이저의 판단과 대화는 대규모 언어 모델이 생성합니다. 본 사이트에서 검증된 데이터만 사용하도록 요구하지만 여전히 오류나 부정확한 표현이 있을 수 있습니다. AI 출력은 참고용입니다.',
      ] },
      { h: '6. 외부 링크', body: [
        '본 사이트가 연결하는 공식 공고·정부 페이지 등 외부 사이트는 제3자가 운영하며 그 내용과 가용성은 당사의 통제 밖에 있습니다.',
      ] },
    ],
  },
}

export default function DisclaimerPage() { return <LegalShell docs={docs} icon={<IconScale />} /> }
