import type { CollectionConfig } from 'payload'

// 职位 — ETL 写入(评分后)。externalId 用于 upsert 去重。
export const Jobs: CollectionConfig = {
  slug: 'jobs',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'company', 'province', 'noc', 'score', 'status'],
    group: 'Data (ETL)',
  },
  fields: [
    { name: 'title', type: 'text', required: true },
    { name: 'company', type: 'relationship', relationTo: 'companies' },
    { name: 'noc', type: 'text', index: true, admin: { description: 'NOC 2021 5位码' } },
    { name: 'category', type: 'text', index: true, admin: { description: 'TEER 标签(=TEER X / 未分类)' } },
    { name: 'teer', type: 'number', index: true, admin: { description: 'NOC 第2位 0-5' } },
    { name: 'broad', type: 'text', index: true, admin: { description: '大分类(NOC 第1位)' } },
    { name: 'mid', type: 'text', index: true, admin: { description: '中分类' } },
    { name: 'fine', type: 'text', admin: { description: '小分类' } },
    { name: 'description', type: 'textarea', admin: { description: '真实抓取的 JD 正文(mart 按 applyUrl 匹配 .md 写入);列表 SQL 不读,只「职位描述」弹框/顾问按需取' } },
    { name: 'country', type: 'text', index: true },
    { name: 'province', type: 'text', index: true },
    { name: 'city', type: 'text' },
    { name: 'district', type: 'text', index: true, admin: { description: '社区/区(Kanata/Nepean/Orléans…)' } },
    { name: 'address', type: 'text', admin: { description: '精确地址(街号+邮编)' } },
    { name: 'region', type: 'text', index: true },
    { name: 'applyUrl', type: 'text', index: true, admin: { description: '第一方投递链接(/api/jobtext 按此等值查询)' } },
    { name: 'officialUrl', type: 'text' },
    { name: 'salary', type: 'text', admin: { description: '原始薪资文本(悬停展示/搜索)' } },
    { name: 'salaryAnnual', type: 'number', index: true, admin: { description: '年薪折算(04d 清洗;排序/vs中位用)' } },
    { name: 'salaryText', type: 'text', admin: { description: '规范薪资文本(04d 清洗,如 $96K–$135K/yr)' } },
    { name: 'wageMedHourly', type: 'number', admin: { description: '该 NOC 当地中位时薪(ESDC 开放数据,省级)' } },
    { name: 'wageMedAnnual', type: 'number', admin: { description: '该 NOC 当地中位年薪(=中位时薪×2080)' } },
    { name: 'wageLowHourly', type: 'number', admin: { description: '该 NOC 当地低位时薪(ESDC，可能缺)' } },
    { name: 'wageLowAnnual', type: 'number', admin: { description: '该 NOC 当地低位年薪' } },
    { name: 'wageHighHourly', type: 'number', admin: { description: '该 NOC 当地高位时薪(ESDC，可能缺)' } },
    { name: 'wageHighAnnual', type: 'number', admin: { description: '该 NOC 当地高位年薪' } },
    { name: 'wageYear', type: 'text', admin: { description: 'ESDC 工资数据参考年份(如 2023-2024)' } },
    { name: 'datePosted', type: 'date' },
    { name: 'source', type: 'text', admin: { description: '原始来源板:indeed.com/Talent.com/lever/bamboohr…' } },
    { name: 'sourceLabel', type: 'text', index: true, admin: { description: '显示来源标签(mart 洗:JB→Job Bank、ATS板美化)' } },
    { name: 'origin', type: 'select', index: true, options: ['jobbank', 'ats', 'directory'], admin: { description: '数据渠道:raw 下哪个来源' } },
    { name: 'isAgency', type: 'checkbox', defaultValue: false },
    { name: 'policyRefs', type: 'relationship', relationTo: 'policy-docs', hasMany: true },
    {
      name: 'accessibility',
      type: 'select',
      defaultValue: 'unknown',
      options: ['co-op', 'junior', 'intermediate', 'senior', 'unknown'],
    },
    { name: 'score', type: 'number', index: true, admin: { description: '移民价值评分 0-100' } },
    { name: 'pnpEligible', type: 'checkbox', index: true, defaultValue: false, admin: { description: '可走雇主offer省提名(TEER0-3 或紧缺低TEER通道)' } },
    { name: 'pnpStream', type: 'text', admin: { description: '命中省提名具名通道的短标签(如「OINP 紧缺技能」),数据层 08_score 算;泛技能岗为空' } },
    { name: 'eeCategory', type: 'text', index: true, admin: { description: '联邦 Express Entry 类别抽选所属类别(医疗社服/STEM/技工…),数据层 08_score 算;与 PNP 是两条路,独立信号' } },
    { name: 'aip', type: 'checkbox', index: true, defaultValue: false, admin: { description: '雇主在官方 AIP 指定雇主名单(大西洋四省 NL/NB/NS/PE)' } },
    // 雇佣形态 + 入职要求(E6-06/E6-07A):Job Bank 详情页结构化标注,05b 规则解析;无标注/ATS=空(宁缺)
    { name: 'employmentTerm', type: 'text', admin: { description: '雇佣期 permanent/term/casual/seasonal;空=未标注' } },
    { name: 'employmentHours', type: 'text', admin: { description: '工时 full/part;空=未标注' } },
    { name: 'certificates', type: 'json', admin: { description: '证书/执照要求 string[](详情页 Certificates 区原文,标准化词表)' } },
    { name: 'education', type: 'text', admin: { description: '学历要求(详情页 Education 区原文,分号连接)' } },
    { name: 'firstSeen', type: 'date' },
    { name: 'lastSeen', type: 'date' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'open',
      index: true,
      options: ['open', 'closed'],
    },
    { name: 'closedAt', type: 'date', admin: { description: '下架时间(某次抓取不再出现)' } },
    { name: 'externalId', type: 'text', unique: true, index: true, admin: { description: 'posting_id,用于增量去重' } },
  ],
}
