import type { CollectionConfig } from 'payload'

// 职位 — ETL 写入(评分后)。externalId 用于 upsert 去重。
export const Jobs: CollectionConfig = {
  slug: 'jobs',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'company', 'province', 'noc', 'score', 'status'],
    group: 'Data (ETL)',
  },
  fields: [
    { name: 'title', type: 'text', required: true },
    { name: 'company', type: 'relationship', relationTo: 'companies' },
    { name: 'noc', type: 'text', index: true, admin: { description: 'NOC 2021 5位码' } },
    { name: 'category', type: 'text', index: true, admin: { description: 'TEER 标签(=TEER X / 未分类)' } },
    { name: 'teer', type: 'number', index: true, admin: { description: 'NOC 第2位 0-5' } },
    { name: 'broad', type: 'text', index: true, admin: { description: '大分类(NOC 第1位)' } },
    { name: 'mid', type: 'text', index: true, admin: { description: '中分类' } },
    { name: 'fine', type: 'text', admin: { description: '小分类' } },
    { name: 'country', type: 'text', index: true },
    { name: 'province', type: 'text', index: true },
    { name: 'city', type: 'text' },
    { name: 'district', type: 'text', index: true, admin: { description: '社区/区(Kanata/Nepean/Orléans…)' } },
    { name: 'address', type: 'text', admin: { description: '精确地址(街号+邮编)' } },
    { name: 'region', type: 'text', index: true },
    { name: 'applyUrl', type: 'text', admin: { description: '第一方投递链接' } },
    { name: 'officialUrl', type: 'text' },
    { name: 'salary', type: 'text', admin: { description: '原始薪资文本(悬停展示/搜索)' } },
    { name: 'salaryAnnual', type: 'number', index: true, admin: { description: '年薪折算(04d 清洗;排序/vs中位用)' } },
    { name: 'salaryText', type: 'text', admin: { description: '规范薪资文本(04d 清洗,如 $96K–$135K/yr)' } },
    { name: 'datePosted', type: 'date' },
    { name: 'source', type: 'text', admin: { description: '原始来源板:indeed.com/Talent.com/lever/bamboohr…' } },
    { name: 'sourceLabel', type: 'text', index: true, admin: { description: '显示来源标签(mart 洗:JB→Job Bank、ATS板美化)' } },
    { name: 'origin', type: 'select', index: true, options: ['jobbank', 'ats', 'directory'], admin: { description: '数据渠道:raw 下哪个来源' } },
    { name: 'isAgency', type: 'checkbox', defaultValue: false },
    { name: 'pnpStreams', type: 'relationship', relationTo: 'pnp-streams', hasMany: true },
    { name: 'policyRefs', type: 'relationship', relationTo: 'policy-docs', hasMany: true },
    {
      name: 'accessibility',
      type: 'select',
      defaultValue: 'unknown',
      options: ['co-op', 'junior', 'intermediate', 'senior', 'unknown'],
    },
    { name: 'score', type: 'number', index: true, admin: { description: '移民价值评分 0-100' } },
    { name: 'pnpEligible', type: 'checkbox', index: true, defaultValue: false, admin: { description: '可走雇主offer省提名(TEER0-3 或紧缺低TEER通道)' } },
    { name: 'aip', type: 'checkbox', index: true, defaultValue: false, admin: { description: '雇主在官方 AIP 指定雇主名单(大西洋四省 NL/NB/NS/PE)' } },
    { name: 'firstSeen', type: 'date' },
    { name: 'lastSeen', type: 'date' },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'open',
      index: true,
      options: ['open', 'closed'],
    },
    { name: 'closedAt', type: 'date', admin: { description: '下架时间(某次抓取不再出现)' } },
    { name: 'externalId', type: 'text', unique: true, index: true, admin: { description: 'posting_id,用于增量去重' } },
  ],
}
